spring.application.name=proyecto-final
# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/gestiON
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# JPA / Hibernate Settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=encriptacionsecreta
jwt.expiration=86400000
app.uploads.dir=/uploads
# Minio configuration
minio.secret-key=
minio.bucket-name=gesti-on
minio.user=admin
minio.password=admin123

